gdb-10.2.patch: Fix duplicated code by re-applying patch
When adding a patch to gdb-10.2.patch, a LOONGARCH64 build will fail
with the following redefinition errors.  There is need to remove the
gdb-10.2 directory before rebuilding.  It's because the patch command
cannot detect previously applied patches for newly created loongarch
files and those files get duplicated code.

  $ git am /tmp/0001-LoongArch64-Fixed-link-errors-when-build-on-LOO.patch
  Applying: LoongArch64: Fixed link errors when build on LOONGARCH64 machine
  $ make -j 16 warn target=LOONGARCH64
  ...
  patching file gdb-10.2/bfd/configure.ac
  Reversed (or previously applied) patch detected!  Skipping patch.
  1 out of 1 hunk ignored
  patching file gdb-10.2/bfd/cpu-loongarch.c   <<-- cannot detect previously applied patch
  patching file gdb-10.2/bfd/elf-bfd.h
  patching file gdb-10.2/bfd/elf.c
  ...
  libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DBINDIR=\"/usr/local/bin\" ...
  cpu-loongarch.c:86:33: error: redefinition of 'bfd_loongarch32_arch'
     static const bfd_arch_info_type bfd_loongarch32_arch =
                                     ^~~~~~~~~~~~~~~~~~~~
  ...
  make: *** [Makefile:254: all] Error 2

To fix this, change the file path of newly created files from "*.orig"
to "/dev/null" so that patch command can detect previously applied
patches.

Signed-off-by: Kazuhito Hagio <k-hagio-ab@nec.com>